# Generated by Django 5.2.1 on 2025-06-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Employee ID. Optional', max_length=255, null=True),
        ),
    ]
