# Generated by Django 5.2.1 on 2025-06-02 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0004_diagnosislist_alter_diagnosis_date_of_diagnosis_and_more'),
        ('providerapp', '0002_provider_employee_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='institution',
            field=models.ForeignKey(help_text='Select the institution for the provider', on_delete=django.db.models.deletion.CASCADE, to='patientapp.institution'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_type',
            field=models.ForeignKey(help_text='Select the provider type', on_delete=django.db.models.deletion.CASCADE, to='providerapp.providertype'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='user',
            field=models.OneToOneField(help_text='Select the user for the provider', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
