# Generated by Django 5.2.1 on 2025-05-13 01:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Construct Scale',
                'verbose_name_plural': 'Construct Scales',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='LikertScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('likert_scale_name', models.CharField(blank=True, help_text='The name of the Likert Scale', max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Likert Scale Response',
                'verbose_name_plural': 'Likert Scale Responses',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='The name of the questionnaire', max_length=255, null=True)),
                ('name_en_gb', models.CharField(blank=True, help_text='The name of the questionnaire', max_length=255, null=True)),
                ('name_bn', models.CharField(blank=True, help_text='The name of the questionnaire', max_length=255, null=True)),
                ('name_hi', models.CharField(blank=True, help_text='The name of the questionnaire', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='The description of the questionnaire', null=True)),
                ('description_en_gb', models.TextField(blank=True, help_text='The description of the questionnaire', null=True)),
                ('description_bn', models.TextField(blank=True, help_text='The description of the questionnaire', null=True)),
                ('description_hi', models.TextField(blank=True, help_text='The description of the questionnaire', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Questionnaire',
                'verbose_name_plural': 'Questionnaires',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='RangeScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('range_scale_name', models.CharField(blank=True, help_text='The name of the Range Scale', max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Range Scale',
                'verbose_name_plural': 'Range Scales',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='The name of the item which will be displayed to the patient', max_length=255, null=True)),
                ('name_en_gb', models.CharField(blank=True, help_text='The name of the item which will be displayed to the patient', max_length=255, null=True)),
                ('name_bn', models.CharField(blank=True, help_text='The name of the item which will be displayed to the patient', max_length=255, null=True)),
                ('name_hi', models.CharField(blank=True, help_text='The name of the item which will be displayed to the patient', max_length=255, null=True)),
                ('response_type', models.CharField(choices=[('Text', 'Text Response'), ('Number', 'Numeric Response'), ('Likert', 'Likert Scale'), ('Range', 'Range Response')], help_text='The type of response for the item', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('construct_scale', models.ForeignKey(help_text='Each item can belong to a construct scale which is designed to measure a construct or domain related to the Patient Reported Outcome.', on_delete=django.db.models.deletion.CASCADE, to='promapp.constructscale')),
                ('likert_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promapp.likertscale')),
                ('range_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promapp.rangescale')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireItemResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_response_text', models.CharField(blank=True, help_text='The response value for the item', max_length=255, null=True)),
                ('item_response_number', models.DecimalField(blank=True, decimal_places=2, help_text='The response value for the item', max_digits=10, null=True)),
                ('item_response_likert_value', models.DecimalField(blank=True, decimal_places=2, help_text='The response value for the item', max_digits=10, null=True)),
                ('item_response_range_min_value', models.DecimalField(blank=True, decimal_places=2, help_text='The minimum value for the item response', max_digits=10, null=True)),
                ('item_response_range_max_value', models.DecimalField(blank=True, decimal_places=2, help_text='The maximum value for the item response', max_digits=10, null=True)),
                ('response_date_time', models.DateTimeField(auto_now_add=True, help_text='The date and time of the response')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promapp.item')),
                ('patient', models.ForeignKey(help_text='The patient to whom the questionnaire belongs', on_delete=django.db.models.deletion.CASCADE, to='patientapp.patient')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promapp.questionnaire')),
            ],
            options={
                'verbose_name': 'Questionnaire Item Response',
                'verbose_name_plural': 'Questionnaire Item Responses',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='RangeScaleResponseOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_value', models.DecimalField(decimal_places=2, help_text='The minimum value for the range scale', max_digits=10)),
                ('min_value_text', models.CharField(blank=True, help_text='The text to display for the minimum value', max_length=255, null=True)),
                ('min_value_text_en_gb', models.CharField(blank=True, help_text='The text to display for the minimum value', max_length=255, null=True)),
                ('min_value_text_bn', models.CharField(blank=True, help_text='The text to display for the minimum value', max_length=255, null=True)),
                ('min_value_text_hi', models.CharField(blank=True, help_text='The text to display for the minimum value', max_length=255, null=True)),
                ('max_value', models.DecimalField(decimal_places=2, help_text='The maximum value for the range scale', max_digits=10)),
                ('max_value_text', models.CharField(blank=True, help_text='The text to display for the maximum value', max_length=255, null=True)),
                ('max_value_text_en_gb', models.CharField(blank=True, help_text='The text to display for the maximum value', max_length=255, null=True)),
                ('max_value_text_bn', models.CharField(blank=True, help_text='The text to display for the maximum value', max_length=255, null=True)),
                ('max_value_text_hi', models.CharField(blank=True, help_text='The text to display for the maximum value', max_length=255, null=True)),
                ('increment', models.DecimalField(blank=True, decimal_places=2, default=1, help_text='The increment for the range scale. Must be more than 0', max_digits=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('range_scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promapp.rangescale')),
            ],
            options={
                'verbose_name': 'Range Scale Response Option',
                'verbose_name_plural': 'Range Scale Response Options',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='LikertScaleResponseOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_text', models.CharField(blank=True, help_text='The text to display for the option', max_length=255, null=True)),
                ('option_text_en_gb', models.CharField(blank=True, help_text='The text to display for the option', max_length=255, null=True)),
                ('option_text_bn', models.CharField(blank=True, help_text='The text to display for the option', max_length=255, null=True)),
                ('option_text_hi', models.CharField(blank=True, help_text='The text to display for the option', max_length=255, null=True)),
                ('option_order', models.IntegerField(blank=True, help_text='The order of the option. This will be a number.', null=True)),
                ('option_media', models.FileField(blank=True, help_text='The media to display for the option. This will be an audio, video or image.', null=True, upload_to='likert_scale_response_options/')),
                ('option_media_en_gb', models.FileField(blank=True, help_text='The media to display for the option. This will be an audio, video or image.', null=True, upload_to='likert_scale_response_options/')),
                ('option_media_bn', models.FileField(blank=True, help_text='The media to display for the option. This will be an audio, video or image.', null=True, upload_to='likert_scale_response_options/')),
                ('option_media_hi', models.FileField(blank=True, help_text='The media to display for the option. This will be an audio, video or image.', null=True, upload_to='likert_scale_response_options/')),
                ('option_value', models.DecimalField(blank=True, decimal_places=2, help_text='The value to store for the option. This will be a number with upto 2 decimal places.', max_digits=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('likert_scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promapp.likertscale')),
            ],
            options={
                'verbose_name': 'Likert Scale Response Option',
                'verbose_name_plural': 'Likert Scale Response Options',
                'ordering': ['option_order'],
                'unique_together': {('option_text', 'option_order', 'option_value')},
            },
        ),
    ]
