# Generated by Django 5.2.1 on 2025-05-16 13:27

import django.db.models.deletion
import parler.fields
import parler.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('instrument_name', models.CharField(blank=True, help_text='The name of the instrument that the construct scale belongs to', max_length=255, null=True)),
                ('instrument_version', models.CharField(blank=True, help_text='The version of the instrument that the construct scale belongs to', max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Construct Scale',
                'verbose_name_plural': 'Construct Scales',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='LikertScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('likert_scale_name', models.CharField(blank=True, help_text='The name of the Likert Scale', max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Likert Scale Response',
                'verbose_name_plural': 'Likert Scale Responses',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Questionnaire',
                'verbose_name_plural': 'Questionnaires',
                'ordering': ['-created_date'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RangeScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('range_scale_name', models.CharField(blank=True, help_text='The name of the Range Scale', max_length=255, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, help_text='The maximum value for the range scale', max_digits=10, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, help_text='The minimum value for the range scale', max_digits=10, null=True)),
                ('increment', models.DecimalField(blank=True, decimal_places=2, help_text='The increment for the range scale. Must be more than 0', max_digits=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Range Scale',
                'verbose_name_plural': 'Range Scales',
                'ordering': ['-created_date'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_type', models.CharField(choices=[('Text', 'Text Response'), ('Number', 'Numeric Response'), ('Likert', 'Likert Scale'), ('Range', 'Range Response')], db_index=True, help_text='The type of response for the item', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('construct_scale', models.ForeignKey(help_text='Each item can belong to a construct scale which is designed to measure a construct or domain related to the Patient Reported Outcome.', on_delete=django.db.models.deletion.CASCADE, to='promapp.constructscale')),
                ('likert_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promapp.likertscale')),
                ('range_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promapp.rangescale')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['-created_date'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LikertScaleResponseOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_order', models.IntegerField(blank=True, help_text='The order of the option. This will be a number.', null=True)),
                ('option_value', models.DecimalField(blank=True, decimal_places=2, help_text='The value to store for the option. This will be a number with upto 2 decimal places.', max_digits=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('likert_scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promapp.likertscale')),
            ],
            options={
                'verbose_name': 'Likert Scale Response Option',
                'verbose_name_plural': 'Likert Scale Response Options',
                'ordering': ['option_order'],
                'unique_together': {('likert_scale', 'option_order', 'option_value')},
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='QuestionnaireItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_number', models.IntegerField(help_text='The number of the question in the questionnaire')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(help_text='The item to which the response belongs', on_delete=django.db.models.deletion.CASCADE, to='promapp.item')),
                ('questionnaire', models.ForeignKey(help_text='The questionnaire to which the response belongs', on_delete=django.db.models.deletion.CASCADE, to='promapp.questionnaire')),
            ],
            options={
                'verbose_name': 'Questionnaire Item Response',
                'verbose_name_plural': 'Questionnaire Item Responses',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, db_index=True, help_text='The name of the item which will be displayed to the patient', max_length=255, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='promapp.item')),
            ],
            options={
                'verbose_name': 'Item Translation',
                'db_table': 'promapp_item_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LikertScaleResponseOptionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('option_text', models.CharField(blank=True, help_text='The text to display for the option', max_length=255, null=True)),
                ('option_media', models.FileField(blank=True, help_text='The media to display for the option. This will be an audio, video or image.', null=True, upload_to='likert_scale_response_options/')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='promapp.likertscaleresponseoption')),
            ],
            options={
                'verbose_name': 'Likert Scale Response Option Translation',
                'db_table': 'promapp_likertscaleresponseoption_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='QuestionnaireTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, help_text='The name of the questionnaire', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='The description of the questionnaire', null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='promapp.questionnaire')),
            ],
            options={
                'verbose_name': 'Questionnaire Translation',
                'db_table': 'promapp_questionnaire_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RangeScaleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('min_value_text', models.CharField(blank=True, help_text='The text to display for the minimum value', max_length=255, null=True)),
                ('max_value_text', models.CharField(blank=True, help_text='The text to display for the maximum value', max_length=255, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='promapp.rangescale')),
            ],
            options={
                'verbose_name': 'Range Scale Translation',
                'db_table': 'promapp_rangescale_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
