# Generated by Django 5.2.1 on 2025-05-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructscale',
            name='instrument_name',
            field=models.CharField(blank=True, help_text='The name of the instrument that the construct scale belongs to', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='constructscale',
            name='instrument_version',
            field=models.CharField(blank=True, help_text='The version of the instrument that the construct scale belongs to', max_length=255, null=True),
        ),
    ]
