# Generated by Django 5.2.1 on 2025-05-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_number',
            field=models.IntegerField(blank=True, help_text='The number of the item in the construct scale', null=True),
        ),
    ]
