# Generated by Django 5.2.1 on 2025-05-12 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='likert_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promapp.likertscale'),
        ),
        migrations.AddField(
            model_name='item',
            name='range_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promapp.rangescale'),
        ),
        migrations.AlterField(
            model_name='item',
            name='response_type',
            field=models.CharField(choices=[('Text', 'Text Response'), ('Number', 'Numeric Response'), ('Likert', 'Likert Scale'), ('Range', 'Range Response')], max_length=255),
        ),
    ]
