# Generated by Django 5.2.1 on 2025-05-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='response_type',
            field=models.CharField(choices=[('Text', 'Text Response'), ('Number', 'Numeric Response'), ('Likert', 'Likert Scale'), ('Range', 'Range Response')], db_index=True, help_text='The type of response for the item', max_length=255),
        ),
        migrations.AlterField(
            model_name='itemtranslation',
            name='name',
            field=models.CharField(blank=True, db_index=True, help_text='The name of the item which will be displayed to the patient', max_length=255, null=True),
        ),
    ]
