# Generated by Django 5.2.1 on 2025-05-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireconstructscore',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The score for the construct', max_digits=10, null=True),
        ),
    ]
