# Generated by Django 5.2.1 on 2025-05-12 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0002_item_likert_response_item_range_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='construct_scale',
            field=models.ForeignKey(help_text='Each item can belong to a construct scale which is designed to measure a construct or domain related to the Patient Reported Outcome.', on_delete=django.db.models.deletion.CASCADE, to='promapp.constructscale'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, help_text='The name of the item which will be displayed to the patient', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='response_type',
            field=models.CharField(choices=[('Text', 'Text Response'), ('Number', 'Numeric Response'), ('Likert', 'Likert Scale'), ('Range', 'Range Response')], help_text='The type of response for the item', max_length=255),
        ),
    ]
