# Generated by Django 5.2.1 on 2025-05-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0002_alter_questionnaireconstructscore_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='likertscaleresponseoption',
            name='option_emoji',
            field=models.CharField(blank=True, help_text='The emoji to display for the option. This will be a string of the emoji.', max_length=255, null=True),
        ),
    ]
