# Generated by Django 5.2.1 on 2025-05-16 14:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0001_initial'),
        ('promapp', '0002_questionnaireresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientQuestionnaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(help_text='The patient to which the questionnaire belongs', on_delete=django.db.models.deletion.CASCADE, to='patientapp.patient')),
                ('questionnaire', models.ForeignKey(help_text='The questionnaire to which the patient belongs', on_delete=django.db.models.deletion.CASCADE, to='promapp.questionnaire')),
            ],
            options={
                'verbose_name': 'Patient Questionnaire',
                'verbose_name_plural': 'Patient Questionnaires',
                'ordering': ['-created_date'],
            },
        ),
    ]
