# Generated by Django 5.2.1 on 2025-05-14 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0002_alter_item_created_date_alter_item_response_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likertscaleresponseoption',
            unique_together={('likert_scale', 'option_order', 'option_value')},
        ),
    ]
