# Generated by Django 5.2.1 on 2025-05-16 14:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0003_patientquestionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireItemResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_date', models.DateTimeField(auto_now_add=True, help_text='The date and time of the response')),
                ('response_value', models.TextField(blank=True, help_text='The response value', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('patient_questionnaire', models.ForeignKey(help_text='The patient questionnaire to which the response belongs', on_delete=django.db.models.deletion.CASCADE, to='promapp.patientquestionnaire')),
                ('questionnaire_item', models.ForeignKey(help_text='The item to which the response belongs', on_delete=django.db.models.deletion.CASCADE, to='promapp.questionnaireitem')),
            ],
            options={
                'verbose_name': 'Questionnaire Response',
                'verbose_name_plural': 'Questionnaire Responses',
                'ordering': ['-response_date'],
            },
        ),
        migrations.DeleteModel(
            name='QuestionnaireResponse',
        ),
    ]
