# Generated by Django 5.2.1 on 2025-05-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0003_likertscaleresponseoption_option_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireconstructscore',
            name='items_answered',
            field=models.IntegerField(blank=True, help_text='The number of items answered for the construct', null=True),
        ),
        migrations.AddField(
            model_name='questionnaireconstructscore',
            name='items_not_answered',
            field=models.IntegerField(blank=True, help_text='The number of items not answered for the construct', null=True),
        ),
    ]
