# Generated by Django 5.2.1 on 2025-05-12 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0001_initial'),
        ('promapp', '0003_alter_item_construct_scale_alter_item_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='The name of the questionnaire', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='The description of the questionnaire', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Questionnaire',
                'verbose_name_plural': 'Questionnaires',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireItemResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_response_text', models.CharField(blank=True, help_text='The response value for the item', max_length=255, null=True)),
                ('item_response_number', models.DecimalField(blank=True, decimal_places=2, help_text='The response value for the item', max_digits=10, null=True)),
                ('item_response_likert_value', models.DecimalField(blank=True, decimal_places=2, help_text='The response value for the item', max_digits=10, null=True)),
                ('item_response_range_min_value', models.DecimalField(blank=True, decimal_places=2, help_text='The minimum value for the item response', max_digits=10, null=True)),
                ('item_response_range_max_value', models.DecimalField(blank=True, decimal_places=2, help_text='The maximum value for the item response', max_digits=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promapp.item')),
                ('patient', models.ForeignKey(help_text='The patient to whom the questionnaire belongs', on_delete=django.db.models.deletion.CASCADE, to='patientapp.patient')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promapp.questionnaire')),
            ],
            options={
                'verbose_name': 'Questionnaire Item Response',
                'verbose_name_plural': 'Questionnaire Item Responses',
                'ordering': ['-created_date'],
            },
        ),
    ]
