# Generated by Django 5.2.1 on 2025-05-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0004_questionnaireitemresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientquestionnaire',
            name='display_questionnaire',
            field=models.BooleanField(default=False, help_text='If True, the questionnaire is currently will be displayed for the patient'),
        ),
    ]
