# Generated by Django 5.2.1 on 2025-05-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0004_questionnaireconstructscore_items_answered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='difficulty_parameter',
            field=models.FloatField(blank=True, help_text='Also known as b index. The difficulty parameter for the item. This value will be obtained from a IRT model like a GPCM model', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='discrimination_parameter',
            field=models.FloatField(blank=True, help_text='Also known as a index. The discrimination parameter for the item. This value will be obtained from a IRT model like a GPCM model', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_required',
            field=models.BooleanField(default=False, help_text='If True, the item is required to be answered for the construct score to be calculated'),
        ),
        migrations.AddField(
            model_name='item',
            name='pseudo_guessing_parameter',
            field=models.FloatField(blank=True, help_text='Also known as c index. The pseudo-guessing parameter for the item. This value will be obtained from a IRT model like a GPCM model', null=True),
        ),
    ]
