# Generated by Django 5.2.1 on 2025-05-12 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0004_questionnaire_questionnaireitemresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireitemresponse',
            name='response_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date and time of the response'),
            preserve_default=False,
        ),
    ]
