# Generated by Django 5.2.1 on 2025-05-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0005_patientquestionnaire_display_questionnaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaireitemresponse',
            old_name='response_value',
            new_name='text_response_value',
        ),
        migrations.AddField(
            model_name='itemtranslation',
            name='media',
            field=models.FileField(blank=True, help_text='The media to display for the item. This will be an audio, video or image.', null=True, upload_to='item_media/'),
        ),
        migrations.AddField(
            model_name='questionnaireitemresponse',
            name='likert_response_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The response value', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='questionnaireitemresponse',
            name='number_response_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The response value', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='questionnaireitemresponse',
            name='range_response_max_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The response value', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='questionnaireitemresponse',
            name='range_response_min_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The response value', max_digits=10, null=True),
        ),
    ]
