# Generated by Django 5.2.1 on 2025-05-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0005_item_difficulty_parameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructscale',
            name='scale_better_score_direction',
            field=models.CharField(blank=True, choices=[('Higher is Better', 'Higher is Better'), ('Lower is Better', 'Lower is Better'), ('Middle is Better', 'Middle is Better'), ('No Direction', 'No Direction')], help_text="The direction of the score for the construct scale. This will be a string of the direction. For example, 'higher is better' or 'lower is better'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='constructscale',
            name='scale_minimum_clinical_important_difference',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The minimum difference between two scores that would be considered clinically important. This is used to calculate the minimum difference between two scores that would be considered clinically important. Changes exceed this magnitude will result in clinically significant impact on patient lives.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='constructscale',
            name='scale_normative_score_mean',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The mean of the normative score for the construct scale. This is used to display the normative score for the construct scale.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='constructscale',
            name='scale_normative_score_standard_deviation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The standard deviation of the normative score for the construct scale. This is used to display the normative score for the construct scale.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='constructscale',
            name='scale_threshold_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The threshold score is the score which is considered to be clinically important. Scores above or below this threshold depending on the direction will be considered to be clinically actionable.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_better_score_direction',
            field=models.CharField(blank=True, choices=[('Higher is Better', 'Higher is Better'), ('Lower is Better', 'Lower is Better'), ('Middle is Better', 'Middle is Better'), ('No Direction', 'No Direction')], help_text="The direction of the score for the item. This will be a string of the direction. For example, 'higher is better' or 'lower is better'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_minimum_clinical_important_difference',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The minimum difference between two scores that would be considered clinically important. This is used to calculate the minimum difference between two scores that would be considered clinically important. Changes exceed this magnitude will result in clinically significant impact on patient lives.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_normative_score_mean',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The mean of the normative score for the item. This is used to display the normative score for the item.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_normative_score_standard_deviation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The standard deviation of the normative score for the item. This is used to display the normative score for the item.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_threshold_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The threshold score is the score which is considered to be clinically important. Scores above or below this threshold depending on the direction will be considered to be clinically actionable.', max_digits=10, null=True),
        ),
    ]
