# Generated by Django 5.2.1 on 2025-05-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0006_rename_response_value_questionnaireitemresponse_text_response_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaireitemresponse',
            name='likert_response_value',
        ),
        migrations.RemoveField(
            model_name='questionnaireitemresponse',
            name='number_response_value',
        ),
        migrations.RemoveField(
            model_name='questionnaireitemresponse',
            name='range_response_max_value',
        ),
        migrations.RemoveField(
            model_name='questionnaireitemresponse',
            name='range_response_min_value',
        ),
        migrations.RemoveField(
            model_name='questionnaireitemresponse',
            name='text_response_value',
        ),
        migrations.AddField(
            model_name='questionnaireitemresponse',
            name='response_value',
            field=models.CharField(blank=True, help_text='The response value', max_length=255, null=True),
        ),
    ]
