# Generated by Django 5.2.1 on 2025-05-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0007_alter_constructscale_scale_better_score_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_missing_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The value to store for the item when it is not answered. This will be a number with upto 2 decimal places.', max_digits=10, null=True),
        ),
    ]
