# Generated by Django 5.2.1 on 2025-05-17 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0007_remove_questionnaireitemresponse_likert_response_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaireitem',
            options={'ordering': ['-created_date'], 'verbose_name': 'Questionnaire Item', 'verbose_name_plural': 'Questionnaire Items'},
        ),
    ]
