# Generated by Django 5.2.1 on 2025-05-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0008_item_item_missing_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_missing_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The value to store for the item when it is not answered. This will be a number with upto 2 decimal places. If left blank then the item value will be a Null when missing. This is usually the correct practice so do not set the value unless the scoring document specifies this explicity.', max_digits=10, null=True),
        ),
    ]
