# Generated by Django 5.2.1 on 2025-05-17 14:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0008_alter_questionnaireitem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireItemRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operator', models.CharField(choices=[('EQUALS', 'Equals'), ('NOT_EQUALS', 'Not Equals'), ('GREATER_THAN', 'Greater Than'), ('LESS_THAN', 'Less Than'), ('GREATER_THAN_EQUALS', 'Greater Than or Equals'), ('LESS_THAN_EQUALS', 'Less Than or Equals'), ('CONTAINS', 'Contains'), ('NOT_CONTAINS', 'Does Not Contain')], max_length=20)),
                ('comparison_value', models.CharField(help_text='The value to compare against', max_length=255)),
                ('logical_operator', models.CharField(choices=[('AND', 'And'), ('OR', 'Or')], default='AND', help_text='How this rule combines with other rules', max_length=3)),
                ('rule_order', models.IntegerField(default=0, help_text='Order in which rules should be evaluated')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('dependent_item', models.ForeignKey(help_text='The previous item whose response determines visibility', on_delete=django.db.models.deletion.CASCADE, related_name='dependent_rules', to='promapp.questionnaireitem')),
                ('questionnaire_item', models.ForeignKey(help_text='The item whose visibility is controlled by this rule', on_delete=django.db.models.deletion.CASCADE, related_name='visibility_rules', to='promapp.questionnaireitem')),
            ],
            options={
                'verbose_name': 'Questionnaire Item Rule',
                'verbose_name_plural': 'Questionnaire Item Rules',
                'ordering': ['rule_order'],
                'unique_together': {('questionnaire_item', 'dependent_item', 'operator', 'comparison_value')},
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireItemRuleGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_order', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('questionnaire_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_groups', to='promapp.questionnaireitem')),
                ('rules', models.ManyToManyField(related_name='rule_groups', to='promapp.questionnaireitemrule')),
            ],
            options={
                'verbose_name': 'Questionnaire Item Rule Group',
                'verbose_name_plural': 'Questionnaire Item Rule Groups',
                'ordering': ['group_order'],
            },
        ),
    ]
