# Generated by Django 5.2.1 on 2025-05-18 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0009_questionnaireitemrule_questionnaireitemrulegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientquestionnaire',
            name='questionnaire_answer_interval',
            field=models.IntegerField(default=0, help_text='The interval in seconds between answering the same questionnaire by the same patient'),
        ),
        migrations.AddField(
            model_name='patientquestionnaire',
            name='questionnaire_order',
            field=models.IntegerField(default=0, help_text='The order of the questionnaire in the list of questionnaires for the patient'),
        ),
        migrations.AddField(
            model_name='patientquestionnaire',
            name='questionnaire_redirect',
            field=models.ForeignKey(blank=True, help_text='The questionnaire to redirect to after the current questionnaire is answered', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redirect_questionnaire', to='promapp.questionnaire'),
        ),
        migrations.AlterField(
            model_name='questionnaireitemrule',
            name='operator',
            field=models.CharField(choices=[('EQUALS', 'Equals'), ('NOT_EQUALS', 'Not Equals'), ('GREATER_THAN', 'Greater Than'), ('LESS_THAN', 'Less Than'), ('GREATER_THAN_EQUALS', 'Greater Than or Equals'), ('LESS_THAN_EQUALS', 'Less Than or Equals'), ('CONTAINS', 'Contains'), ('NOT_CONTAINS', 'Does Not Contain')], help_text='The operator to use for the comparison', max_length=40),
        ),
    ]
