# Generated by Django 5.2.1 on 2025-05-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0009_alter_item_item_missing_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireconstructscore',
            name='calculation_log',
            field=models.TextField(blank=True, help_text='The log of the equation processing', null=True),
        ),
        migrations.AddField(
            model_name='questionnaireconstructscorecomposite',
            name='calculation_log',
            field=models.TextField(blank=True, help_text='The log of the equation processing', null=True),
        ),
    ]
