# Generated by Django 5.2.1 on 2025-05-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0010_patientquestionnaire_questionnaire_answer_interval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientquestionnaire',
            name='questionnaire_answer_interval',
        ),
        migrations.RemoveField(
            model_name='patientquestionnaire',
            name='questionnaire_order',
        ),
        migrations.RemoveField(
            model_name='patientquestionnaire',
            name='questionnaire_redirect',
        ),
    ]
