# Generated by Django 5.2.1 on 2025-06-02 05:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0010_questionnaireconstructscore_calculation_log_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likertscale',
            options={'ordering': ['-created_date'], 'verbose_name': 'Likert Scale', 'verbose_name_plural': 'Likert Scales'},
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='questionnaire_answer_interval',
            field=models.IntegerField(default=0, help_text='The interval in seconds between answering the same questionnaire by the same patient. Set to 0 to allow immediate re-answering.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
