# Generated by Django 5.2.1 on 2025-06-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0011_alter_likertscale_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtranslation',
            name='media',
            field=models.FileField(blank=True, help_text='The media to display for the item. This will be an audio, video or image. Allowed files are <br> <ul> <li>Audio: .mp3, .wav, .m4a, .ogg, .flac, .aac</li> <li>Video: .mp4, .mov, .avi, .wmv, .flv, .mkv</li> <li>Image: .jpg, .jpeg, .png, .gif, .bmp, .tiff, .webp</li> </ul> ', null=True, upload_to='item_media/'),
        ),
    ]
