# Generated by Django 5.2.1 on 2025-05-18 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0011_remove_patientquestionnaire_questionnaire_answer_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='questionnaire_answer_interval',
            field=models.IntegerField(default=0, help_text='The interval in seconds between answering the same questionnaire by the same patient'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='questionnaire_order',
            field=models.IntegerField(default=0, help_text='The order of the questionnaire in the list of questionnaires for the patient'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='questionnaire_redirect',
            field=models.ForeignKey(blank=True, help_text='The questionnaire to redirect to after the current questionnaire is answered', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redirect_questionnaire', to='promapp.questionnaire'),
        ),
    ]
