# Generated by Django 5.2.1 on 2025-05-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0012_questionnaire_questionnaire_answer_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructscale',
            name='scale_equation',
            field=models.CharField(blank=True, help_text='The equation to calculate the score for the construct scale from the items in the scale', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='constructscale',
            name='scale_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The value of the construct scale calculated from the items in the scale', max_digits=10, null=True),
        ),
    ]
