# Generated by Django 5.2.1 on 2025-05-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0013_constructscale_scale_equation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructscale',
            name='scale_value',
        ),
        migrations.AddField(
            model_name='constructscale',
            name='minimum_number_of_items',
            field=models.IntegerField(default=0, help_text='The minimum number of items that must be answered to calculate the score for the construct scale'),
        ),
    ]
