# Generated by Django 5.2.2 on 2025-07-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0014_questionnaireitemresponse_response_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='abbreviated_item_id',
            field=models.CharField(blank=True, help_text='The unique abbreviation of the item which will be used for exports. Allowed lower case characters, numbers and underscores. This is not displayed to the patient. For example question of EORTC QLQ C30 may be qlqc30_q1', max_length=255, null=True, unique=True),
        ),
    ]
