# Generated by Django 5.2.4 on 2025-09-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0015_item_abbreviated_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='abbreviated_item_id',
            field=models.CharField(blank=True, help_text='The unique abbreviation of the item which will be used for exports. Allowed lower case characters, numbers and underscores. This is not displayed to the patient. For example question of EORTC QLQ C30 may be qlqc30_q1', max_length=255, null=True, unique=True, verbose_name='Item (Question) Abbreviation To be used'),
        ),
        migrations.AlterField(
            model_name='itemtranslation',
            name='media',
            field=models.FileField(blank=True, help_text='The media to display for the item. This will be an audio, video or image. Allowed files are <br> <ul> <li>Audio: .mp3, .wav, .m4a, .ogg, .flac, .aac</li> <li>Video: .mp4, .mov, .avi, .wmv, .flv, .mkv</li> <li>Image: .jpg, .jpeg, .png, .gif, .bmp, .tiff, .webp</li> </ul> ', null=True, upload_to='item_media/', verbose_name='Item (Question) Media File'),
        ),
        migrations.AlterField(
            model_name='itemtranslation',
            name='name',
            field=models.CharField(blank=True, db_index=True, help_text='The name of the item which will be displayed to the patient', max_length=255, null=True, verbose_name='Item (Question) Text'),
        ),
    ]
