# Generated by Django 5.2.6 on 2025-09-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0016_alter_item_abbreviated_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructscale',
            name='instrument_name',
            field=models.CharField(blank=True, help_text='The name of the patient reported outcome measurement instrument (Questionnaire) that the construct scale belongs to. For example EORTC QLQ C30', max_length=255, null=True, verbose_name='Name of the Instrument (Questionnaire)'),
        ),
        migrations.AlterField(
            model_name='constructscale',
            name='instrument_version',
            field=models.CharField(blank=True, help_text='The version of the instrument that the construct scale belongs to', max_length=255, null=True, verbose_name='Version of the Instrument (Questionnaire)'),
        ),
        migrations.AlterField(
            model_name='constructscale',
            name='minimum_number_of_items',
            field=models.IntegerField(default=0, help_text='The minimum number of items that must be answered to calculate the score for the construct scale', verbose_name='Minimum Number of Items'),
        ),
        migrations.AlterField(
            model_name='constructscale',
            name='name',
            field=models.CharField(blank=True, help_text='Enter the name of the construct scale like physical functioning, pain etc.', max_length=255, null=True, verbose_name='Name of the Construct Scale'),
        ),
        migrations.AlterField(
            model_name='constructscale',
            name='scale_better_score_direction',
            field=models.CharField(blank=True, choices=[('Higher is Better', 'Higher is Better'), ('Lower is Better', 'Lower is Better'), ('Middle is Better', 'Middle is Better'), ('No Direction', 'No Direction')], help_text='Indicates whether higher or lower scores are better for this construct', max_length=255, null=True, verbose_name='Construct Score Direction'),
        ),
        migrations.AlterField(
            model_name='constructscale',
            name='scale_equation',
            field=models.CharField(blank=True, help_text='The equation to calculate the score for the construct scale from the items in the scale', max_length=255, null=True, verbose_name='Equation'),
        ),
        migrations.AlterField(
            model_name='constructscale',
            name='scale_minimum_clinical_important_difference',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The minimum difference between two scores that would be considered clinically important. Changes exceeding this magnitude will result in clinically significant.', max_digits=10, null=True, verbose_name='Minimum Important Difference Score (MID)'),
        ),
        migrations.AlterField(
            model_name='constructscale',
            name='scale_normative_score_mean',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The mean of the normative score for the construct scale. Used to display the normative score reference.', max_digits=10, null=True, verbose_name='Construct Normative Score Mean'),
        ),
        migrations.AlterField(
            model_name='constructscale',
            name='scale_normative_score_standard_deviation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The standard deviation of the normative score for the construct scale. Used to display the normative score reference.', max_digits=10, null=True, verbose_name='Construct Normative Score Standard Deviation'),
        ),
        migrations.AlterField(
            model_name='constructscale',
            name='scale_threshold_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The score which is considered clinically important. Scores above or below this threshold (depending on direction) will be considered clinically actionable.', max_digits=10, null=True, verbose_name='Construct Threshold Score'),
        ),
    ]
