# Generated by Django 5.2.7 on 2025-10-16 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0017_alter_constructscale_instrument_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairesubmission',
            name='user_submitting_questionnaire',
            field=models.ForeignKey(blank=True, help_text='The user submitting the questionnaire', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
