# Generated by Django 5.2.7 on 2025-10-16 13:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0018_questionnairesubmission_user_submitting_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairesubmission',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time of the submission'),
        ),
    ]
