# Generated by Django 5.2.7 on 2025-10-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0019_alter_questionnairesubmission_submission_date'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='item_construct_resptype_idx',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='item_construct_number_idx',
        ),
        migrations.RemoveField(
            model_name='item',
            name='construct_scale',
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['response_type'], name='item_resptype_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['item_number'], name='item_number_idx'),
        ),
        migrations.AddField(
            model_name='item',
            name='construct_scale',
            field=models.ManyToManyField(help_text='Each item can belong to a construct scale which is designed to measure a construct or domain related to the Patient Reported Outcome.', to='promapp.constructscale'),
        ),
    ]
