# Generated by Django 5.2.7 on 2025-10-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0020_remove_item_item_construct_resptype_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructscale',
            name='scale_equation',
            field=models.CharField(blank=True, help_text='The equation to calculate the score for the construct scale from the items in the scale', max_length=1025, null=True, verbose_name='Equation'),
        ),
    ]
