# Generated by Django 5.2.7 on 2025-10-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0021_alter_constructscale_scale_equation'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositeconstructscalescoring',
            name='composite_construct_scale_minimum_clinical_important_difference',
            field=models.CharField(blank=True, help_text='The minimum important difference for the composite construct scale', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='compositeconstructscalescoring',
            name='composite_construct_scale_normative_score_mean',
            field=models.CharField(blank=True, help_text='The normative score mean for the composite construct scale', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='compositeconstructscalescoring',
            name='composite_construct_scale_normative_score_standard_deviation',
            field=models.CharField(blank=True, help_text='The normative score standard deviation for the composite construct scale', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='compositeconstructscalescoring',
            name='composite_construct_scale_threshold_score',
            field=models.CharField(blank=True, help_text='The threshold score for the composite construct scale', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='compositeconstructscalescoring',
            name='composite_construct_score_direction',
            field=models.CharField(blank=True, choices=[('Higher is Better', 'Higher is Better'), ('Lower is Better', 'Lower is Better'), ('Middle is Better', 'Middle is Better'), ('No Direction', 'No Direction')], help_text='Indicates whether higher or lower scores are better for this composite construct', max_length=255, null=True, verbose_name='Composite Construct Score Direction'),
        ),
    ]
