# Generated by Django 5.2.7 on 2025-10-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0022_compositeconstructscalescoring_composite_construct_scale_minimum_clinical_important_difference_and_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtranslation',
            name='name',
            field=models.CharField(blank=True, db_index=True, help_text='The name of the item which will be displayed to the patient', max_length=500, null=True, verbose_name='Item (Question) Text'),
        ),
    ]
