# Generated by Django 6.0.3 on 2026-03-16 09:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0023_alter_itemtranslation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnairePatientSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_assessment', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('patient_questionnaire', models.ForeignKey(help_text='Scheduled Date of Assesement for the Patient', on_delete=django.db.models.deletion.CASCADE, to='promapp.patientquestionnaire')),
            ],
            options={
                'verbose_name': 'Schedule for Patient Questionnaire',
                'verbose_name_plural': 'Schedules for Patient Questionnaire',
            },
        ),
    ]
