# Generated by Django 6.0.3 on 2026-03-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0024_questionnairepatientschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairepatientschedule',
            name='date_assessment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
