# Generated by Django 6.0.3 on 2026-03-26 01:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0025_alter_questionnairepatientschedule_date_assessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAPIConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_provider', models.CharField(help_text='The AI provider', max_length=255)),
                ('ai_capability', models.CharField(blank=True, choices=[('Text To Speech', 'Text To Speech'), ('Speech To Text', 'Speech To Text'), ('Image Generation', 'Image Generation'), ('Video Generation', 'Video Generation'), ('Text Generation', 'Text Generation')], help_text='The AI capability which will be used for this task', max_length=255, null=True)),
                ('api_url', models.CharField(blank=True, help_text='The AI API URL', max_length=512, null=True)),
                ('api_key_environment_variable_name', models.CharField(blank=True, help_text='The name of the environment variable which will be used to store the API Key for the AI model', max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI API Configuration',
                'verbose_name_plural': 'AI API Configurations',
                'ordering': ['-created_date'],
            },
        ),
    ]
