# Generated by Django 6.0.3 on 2026-03-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0026_aiapiconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiapiconfiguration',
            name='api_key_environment_variable_name',
            field=models.CharField(blank=True, help_text='The name of the environment variable which will be used to store the API Key for the AI model. Note that this field is for the name of the variable where the KEY is being stored in the environment not the key itself', max_length=255, null=True),
        ),
    ]
