# Generated by Django 6.0.3 on 2026-03-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0027_alter_aiapiconfiguration_api_key_environment_variable_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiapiconfiguration',
            name='utility_function_path',
            field=models.CharField(help_text="Python import path to the utility function (e.g., 'promapp.ai_utils.sarvamai_tts.sarvam_tts')", max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='aiapiconfiguration',
            name='api_url',
            field=models.CharField(blank=True, help_text='The AI API URL. Can be left blank if using a library', max_length=512, null=True),
        ),
    ]
