# Generated by Django 6.0.5 on 2026-05-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0028_aiapiconfiguration_utility_function_path_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemtranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='likertscaleresponseoptiontranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='questionnairetranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rangescaletranslation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='itemtranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='promapp_item_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='likertscaleresponseoptiontranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='promapp_likertscaleresponseoption_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='questionnairetranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='promapp_questionnaire_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='rangescaletranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='promapp_rangescale_translation_uniq_lang'),
        ),
    ]
