# Generated by Django 5.2.1 on 2025-05-28 02:02

import secured_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='date_of_diagnosis',
            field=secured_fields.fields.EncryptedDateField(blank=True, null=True, searchable=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_registration',
            field=secured_fields.fields.EncryptedDateField(blank=True, null=True, searchable=True, verbose_name='Date of Registration'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='date_of_end_of_treatment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
