# Generated by Django 5.2.1 on 2025-05-28 02:18

import secured_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0002_diagnosis_date_of_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='date_of_diagnosis',
            field=secured_fields.fields.EncryptedDateField(blank=True, null=True, searchable=True, verbose_name='Date of Diagnosis'),
        ),
    ]
