# Generated by Django 5.2.1 on 2025-05-28 04:41

import django.db.models.deletion
import secured_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0003_alter_diagnosis_date_of_diagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnosis', models.CharField(blank=True, max_length=255, null=True)),
                ('icd_11_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='ICD 11 Code')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'List of Diagnosis',
                'verbose_name_plural': 'List of Diagnoses',
                'ordering': ['-created_date'],
            },
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='date_of_diagnosis',
            field=secured_fields.fields.EncryptedDateField(blank=True, help_text='Select the Date of Diagnosis from the calendar', null=True, searchable=True, verbose_name='Date of Diagnosis'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis',
            field=models.ForeignKey(blank=True, help_text='Select the Diagnosis from the list', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_list', to='patientapp.diagnosislist'),
        ),
    ]
