# Generated by Django 5.2.1 on 2025-06-05 02:07

import secured_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0004_diagnosislist_alter_diagnosis_date_of_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='date_of_end_of_treatment',
            field=secured_fields.fields.EncryptedDateField(blank=True, help_text='Select the Date of End of Treatment from the calendar', null=True, searchable=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='date_of_start_of_treatment',
            field=secured_fields.fields.EncryptedDateField(blank=True, help_text='Select the Date of Start of Treatment from the calendar', null=True, searchable=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_type',
            field=models.ManyToManyField(blank=True, help_text='Select the Treatment Type(s) from the list. Please select treatments that have been delivered synchronously.Please add another treatment entry form if there were sequential treatments delivered.', to='patientapp.treatmenttype'),
        ),
    ]
