# Generated by Django 5.2.1 on 2025-06-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0005_alter_treatment_date_of_end_of_treatment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='currently_ongoing_treatment',
            field=models.BooleanField(default=False, help_text='Select this if the treatment is currently ongoing. This will be used to indicate that the treatment is ongoing and not yet completed.'),
        ),
    ]
