# Generated by Django 5.2.1 on 2025-06-05 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0006_treatment_currently_ongoing_treatment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('Non-binary', 'Non Binary'), ('Prefer not to say', 'Prefer Not To Say'), ('Other', 'Other')], db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['patient', 'date_of_diagnosis'], name='diag_patient_date_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['diagnosis', 'date_of_diagnosis'], name='diag_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['institution', 'gender'], name='patient_inst_gender_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['institution', 'age'], name='patient_inst_age_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['institution', 'created_date'], name='patient_inst_created_idx'),
        ),
    ]
