# Generated by Django 5.2.7 on 2025-10-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0007_alter_patient_age_alter_patient_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en-gb', 'English'), ('bn', 'Bengali'), ('hi', 'Hindi'), ('kn', 'Kannada')], db_index=True, max_length=255, null=True),
        ),
    ]
