# Generated by Django 5.2.7 on 2025-10-02 14:15

import django.db.models.deletion
import secured_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0008_patient_preferred_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Please enter the Age of the Patient', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_registration',
            field=secured_fields.fields.EncryptedDateField(blank=True, help_text='Please select the Date of Registration from the Calendar', null=True, searchable=True, verbose_name='Date of Registration'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('Non-binary', 'Non Binary'), ('Prefer not to say', 'Prefer Not To Say'), ('Other', 'Other')], db_index=True, help_text='Please select the Gender of the Patient', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='institution',
            field=models.ForeignKey(help_text='Please select the Institution from the List', on_delete=django.db.models.deletion.CASCADE, to='patientapp.institution'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=secured_fields.fields.EncryptedCharField(blank=True, help_text='Please enter the Full Name of the Patient', max_length=255, null=True, searchable=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=secured_fields.fields.EncryptedCharField(blank=True, help_text='Please enter the Patient ID', max_length=255, null=True, searchable=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en-gb', 'English'), ('bn', 'Bengali'), ('hi', 'Hindi'), ('kn', 'Kannada')], db_index=True, default='en-gb', help_text='Please select the Preferred Language of the Patient', max_length=10, null=True),
        ),
    ]
