# Generated by Django 5.2.7 on 2025-10-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0009_alter_patient_age_alter_patient_date_of_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en-gb', 'English'), ('bn', 'Bangla'), ('hi', 'Hindi')], db_index=True, default='en-gb', help_text='Please select the Preferred Language of the Patient', max_length=10, null=True),
        ),
    ]
