# Generated by Django 5.2.12 on 2026-03-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0011_alter_patient_preferred_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en-gb', 'English'), ('bn', 'Bengali'), ('hi', 'Hindi')], db_index=True, default='en-gb', help_text='Please select the Preferred Language of the Patient', max_length=10, null=True),
        ),
    ]
