# Generated by Django 6.0.3 on 2026-03-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0012_alter_patient_preferred_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en-gb', 'English'), ('bn', 'Bengali'), ('hi', 'Hindi'), ('kn', 'Kannada')], db_index=True, default='en-gb', help_text='Please select the Preferred Language of the Patient', max_length=10, null=True),
        ),
    ]
