# Generated by Django 6.0.5 on 2026-05-17 12:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0013_alter_patient_preferred_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=512, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Institutions',
                'ordering': ['-created_date'],
            },
        ),
        migrations.AlterField(
            model_name='patient',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en-gb', 'English'), ('bn', 'Bengali'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('ne', 'Nepali'), ('dz', 'Dzongkha')], db_index=True, default='en-gb', help_text='Please select the Preferred Language of the Patient', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='PatientProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_patient_enrolled_in_project', models.DateField(blank=True, null=True)),
                ('date_patient_exited_from_project', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patientapp.patient')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.project')),
            ],
            options={
                'verbose_name': 'Patient Project',
                'verbose_name_plural': 'Patient Projects',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['patient', 'project'], name='patient_project_idx')],
            },
        ),
    ]
