# Generated by Django 6.0.5 on 2026-05-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0014_project_alter_patient_preferred_language_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_date'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddConstraint(
            model_name='patientproject',
            constraint=models.UniqueConstraint(condition=models.Q(('patient__isnull', False)), fields=('patient', 'project'), name='unique_patient_project'),
        ),
    ]
