# Generated by Django 6.0.5 on 2026-05-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0015_alter_project_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patientproject',
            name='unique_patient_project',
        ),
        migrations.AddConstraint(
            model_name='patientproject',
            constraint=models.UniqueConstraint(fields=('patient', 'project'), name='unique_patient_project'),
        ),
    ]
