# Generated by Django 6.0.5 on 2026-05-21 00:28

import django.db.models.deletion
import secured_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0016_remove_patientproject_unique_patient_project_and_more'),
        ('promapp', '0028_aiapiconfiguration_utility_function_path_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRedcapMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redcap_project_url', models.URLField()),
                ('redcap_project_token', secured_fields.fields.EncryptedTextField()),
                ('redcap_project_token_allows_import', models.BooleanField(default=False, help_text='Select if the token allows data to be imported into REDCap. Most default API tokens do not allow this so please check your API key settings in REDCap.')),
                ('redcap_project_token_allows_export', models.BooleanField(default=True, help_text='Select if the token allows data to be exported from REDCap. Most default API tokens allow export so this is enabled by default.')),
                ('redcap_project_info', models.JSONField(blank=True, help_text='This is the project information that will be automatically extracted from REDCap after the project settings are filled.', null=True)),
                ('date_redcap_project_info_updated', models.DateField(blank=True, null=True)),
                ('redcap_record_count', models.IntegerField(blank=True, help_text='This is the record count that will be automatically extracted from REDCap after the project settings are filled.', null=True)),
                ('export_type', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=12)),
                ('redcap_study_id_field', models.CharField(blank=True, help_text='This is the name of the field in the project that denotes the study ID.', max_length=1024, null=True)),
                ('redcap_secondary_id_field', models.CharField(blank=True, help_text='This is a secondary unique ID field that is often used when we are using automatic numbering of records in REDCap. Note that this is not going to be used for the import but will be helpful when deciding the study ID to which the data should be imported in REDCap.', max_length=1024, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.project')),
            ],
            options={
                'verbose_name': 'Project Redcap Mapping',
                'verbose_name_plural': 'Project Redcap Mappings',
            },
        ),
        migrations.CreateModel(
            name='RedcapFormToQuestionnaireMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redcap_form_name', models.CharField(max_length=1024)),
                ('redcap_event_name', models.CharField(blank=True, help_text='The REDCap event name for this form. Required when the form is part of a longitudinal event and will be included in CSV exports.', max_length=1024, null=True)),
                ('redcap_form_is_repeating', models.BooleanField(default=False, help_text='This defines if the REDCap form is a repeating form. Repeating form data has to be handled differently from non-repeating forms.')),
                ('redcap_form_is_in_event', models.BooleanField(default=False, help_text='This defines if the REDCap form is a part of an event in a longitudinal project. For these forms the event name needs to be a part of the export file.')),
                ('redcap_event_is_repeating', models.BooleanField(default=False, help_text='This defines if the REDCap event is repeating. If there is a repeating event then all forms in the event will also repeat.')),
                ('redcap_date_mapping_field', models.CharField(blank=True, help_text='This is the field in the REDCap form that will be used to map the date to the questionnaire. Note that this field may exist in another form where the visit date is recorded.', max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('project_redcap_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.projectredcapmapping')),
                ('questionnaire', models.ForeignKey(help_text='Link to the Questionnaire in the CHAVI PROM application.', on_delete=django.db.models.deletion.CASCADE, to='promapp.questionnaire')),
            ],
            options={
                'verbose_name': 'REDCap Form To Questionnaire Mapping',
                'verbose_name_plural': 'REDCap Form To Questionnaire Mappings',
            },
        ),
        migrations.CreateModel(
            name='RedcapFieldToItemMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redcap_field_name', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('questionnaire_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promapp.questionnaireitem')),
                ('redcap_form_to_questionnaire_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.redcapformtoquestionnairemapping')),
            ],
            options={
                'verbose_name': 'REDCap Field To Item Mapping',
                'verbose_name_plural': 'REDCap Field To Item Mappings',
            },
        ),
        migrations.CreateModel(
            name='RedcapDataExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', help_text='Whether this was an API-mediated export or a manual CSV export.', max_length=12)),
                ('datetime_export_start', models.DateTimeField(blank=True, null=True)),
                ('datetime_export_completed', models.DateTimeField(blank=True, null=True)),
                ('export_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('incomplete', 'Incomplete'), ('failed', 'Failed')], max_length=20, null=True)),
                ('export_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, help_text='The patient whose data was exported.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='patientapp.patient')),
                ('user_exporting_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('redcap_form_to_questionnaire_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.redcapformtoquestionnairemapping')),
            ],
            options={
                'verbose_name': 'REDCap API Data Export Log',
                'verbose_name_plural': 'REDCap API Data Export Logs',
            },
        ),
        migrations.CreateModel(
            name='RedcapStudyIDtoPatientIDMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redcap_study_id', models.CharField(blank=True, help_text='Mapped Study ID from REDCap', max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientapp.patient')),
                ('project_redcap_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientapp.projectredcapmapping')),
            ],
            options={
                'verbose_name': 'REDCap Study ID to Patient ID Map',
                'verbose_name_plural': 'REDCap Study ID to Patient ID Maps',
            },
        ),
        migrations.AddConstraint(
            model_name='projectredcapmapping',
            constraint=models.UniqueConstraint(fields=('project', 'redcap_project_url'), name='unique_project_redcap_url'),
        ),
        migrations.AddConstraint(
            model_name='redcapformtoquestionnairemapping',
            constraint=models.CheckConstraint(condition=models.Q(('redcap_form_is_in_event', True), ('redcap_event_is_repeating', False), _connector='OR'), name='patientapp_redcapformtoquestionnairemapping_event_repeating_requires_in_event', violation_error_message='Event cannot be repeating if form is not in an event.'),
        ),
        migrations.AddConstraint(
            model_name='redcapformtoquestionnairemapping',
            constraint=models.CheckConstraint(condition=models.Q(('redcap_form_is_in_event', False), models.Q(('redcap_date_mapping_field__gt', ''), ('redcap_date_mapping_field__isnull', False)), _connector='OR'), name='patientapp_redcapformtoquestionnairemapping_date_mapping_required_for_events', violation_error_message='Date mapping field is required when form is in an event.'),
        ),
        migrations.AddConstraint(
            model_name='redcapformtoquestionnairemapping',
            constraint=models.UniqueConstraint(fields=('project_redcap_mapping', 'redcap_form_name', 'questionnaire'), name='unique_redcap_form_questionnaire_mapping'),
        ),
        migrations.AddConstraint(
            model_name='redcapfieldtoitemmapping',
            constraint=models.UniqueConstraint(fields=('redcap_form_to_questionnaire_mapping', 'redcap_field_name'), name='unique_redcap_field_per_form_mapping'),
        ),
        migrations.AddConstraint(
            model_name='redcapfieldtoitemmapping',
            constraint=models.UniqueConstraint(fields=('redcap_form_to_questionnaire_mapping', 'questionnaire_item'), name='unique_questionnaire_item_per_form_mapping'),
        ),
        migrations.AddConstraint(
            model_name='redcapstudyidtopatientidmap',
            constraint=models.UniqueConstraint(fields=('project_redcap_mapping', 'patient'), name='unique_redcap_patient_mapping'),
        ),
    ]
