# Generated by Django 6.0.5 on 2026-05-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0017_projectredcapmapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectredcapmapping',
            name='redcap_data_access_group_used',
            field=models.BooleanField(default=False, help_text='Select if a data access group is used in the project.'),
        ),
    ]
