# Generated by Django 6.0.5 on 2026-05-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0019_redcapfieldtoitemmapping_submission_date_field_and_more'),
        ('promapp', '0028_aiapiconfiguration_utility_function_path_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='redcapfieldtoitemmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('submission_date_field__isnull', False)), fields=('redcap_form_to_questionnaire_mapping',), name='unique_submission_date_field_per_form_mapping'),
        ),
    ]
