# Generated by Django 6.0.5 on 2026-05-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0020_redcapfieldtoitemmapping_unique_submission_date_field_per_form_mapping'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='redcapfieldtoitemmapping',
            name='unique_submission_date_field_per_form_mapping',
        ),
        migrations.AddField(
            model_name='redcapformtoquestionnairemapping',
            name='submission_date_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='redcapformtoquestionnairemapping',
            name='submission_date_format',
            field=models.CharField(blank=True, choices=[('date_ymd', 'Date (Y-M-D)'), ('datetime_ymd', 'Datetime (Y-M-D H:M)'), ('datetime_seconds_ymd', 'Datetime w/ seconds (Y-M-D H:M:S)')], help_text='This is the type of date format that will be used to store the submission date in REDCap. The questionnaire submission date will have to be stored in this specific format for the export to work.', max_length=1024, null=True),
        ),
    ]
