# Generated by Django 6.0.5 on 2026-05-21 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0021_remove_redcapfieldtoitemmapping_unique_submission_date_field_per_form_mapping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redcapfieldtoitemmapping',
            name='submission_date_field',
        ),
        migrations.RemoveField(
            model_name='redcapfieldtoitemmapping',
            name='submission_date_format',
        ),
    ]
