# Generated by Django 6.0.5 on 2026-05-22 01:36

import django.db.models.deletion
import secured_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0022_remove_redcapfieldtoitemmapping_submission_date_field_and_more'),
        ('promapp', '0028_aiapiconfiguration_utility_function_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redcapstudyidtopatientidmap',
            name='redcap_study_id',
            field=secured_fields.fields.EncryptedCharField(blank=True, help_text='Mapped Study ID from REDCap', max_length=1024, null=True),
        ),
        migrations.CreateModel(
            name='RedcapSubmissionInstanceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_access_group', models.CharField(blank=True, help_text='Data access group for the questionnaire submission.', max_length=1024, null=True)),
                ('redcap_patient_id', secured_fields.fields.EncryptedCharField(blank=True, help_text='Encrypted REDCap patient ID for the questionnaire submission. Note that as this is an identifying data it is being stored as an encrypted character field.', max_length=1024, null=True)),
                ('redcap_event_name', models.CharField(blank=True, help_text=' Recap event name if this data will be exported into a longitudinal project with events and arms', max_length=1024, null=True)),
                ('redcap_repeat_instance', models.PositiveIntegerField(blank=True, help_text='Repeat instance if this data will be exported into a longitudinal project with events and arms', null=True)),
                ('redcap_repeat_event', models.PositiveIntegerField(blank=True, help_text='ID of the REDCap repeat event it is applicable', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('questionnaire_submission', models.ForeignKey(help_text='Specific instance of the questionnaire submission that will be exported to the REDCap form. Note that the questionnaire submission is linked to the user which in turn links to a patient. Hence the patient is implicitly linked through this relationship.', on_delete=django.db.models.deletion.CASCADE, to='promapp.questionnairesubmission')),
                ('redcap_form', models.ForeignKey(help_text='Specific REDCap form that the questionnaire submission will be exported to. Note that the question to item matching is being done through the RedcapFieldToItemMapping model. Submission date mapping to specific field for noting the date of quality of life will be done using the relationship between the QuestionnaireSubmission model and the RedcapFormToQuestionnaireMapping model here.', on_delete=django.db.models.deletion.CASCADE, to='patientapp.redcapformtoquestionnairemapping')),
            ],
            options={
                'verbose_name': 'REDCap Submission Instance Mapping',
                'verbose_name_plural': 'REDCap Submission Instance Mappings',
            },
        ),
    ]
