# Generated by Django 6.0.5 on 2026-05-22 01:37

import secured_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0023_alter_redcapstudyidtopatientidmap_redcap_study_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectredcapmapping',
            name='redcap_project_info',
            field=secured_fields.fields.EncryptedJSONField(blank=True, help_text='This is the project information that will be automatically extracted from REDCap after the project settings are filled.', null=True),
        ),
    ]
