# Generated by Django 6.0.5 on 2026-05-22 01:39

import secured_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0024_alter_projectredcapmapping_redcap_project_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectredcapmapping',
            name='redcap_project_info',
            field=secured_fields.fields.EncryptedTextField(blank=True, help_text='This is the project information that will be automatically extracted from REDCap after the project settings are filled.', null=True),
        ),
    ]
