# Generated by Django 6.0.5 on 2026-05-22 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0026_alter_projectredcapmapping_redcap_project_info'),
        ('promapp', '0028_aiapiconfiguration_utility_function_path_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RedcapSubmissionInstanceMapping',
            new_name='RedcapInstanceToSubmissionMapping',
        ),
    ]
