# Generated by Django 6.0.5 on 2026-05-22 01:54
#
# Hand-edited: the column contains Fernet-encrypted text which PostgreSQL
# rejects when trying to cast back to jsonb.  We NULL the column first so
# the subsequent AlterField / RemoveField can proceed without a cast error.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0027_rename_redcapsubmissioninstancemapping_redcapinstancetosubmissionmapping'),
    ]

    operations = [
        # Clear encrypted values so Postgres can alter the jsonb column safely.
        migrations.RunSQL(
            sql="UPDATE patientapp_projectredcapmapping SET redcap_project_info = NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='projectredcapmapping',
            name='redcap_project_info',
            field=models.JSONField(blank=True, help_text='This is the project information that will be automatically extracted from REDCap after the project settings are filled.', null=True),
        ),
    ]
