# Generated by Django 6.0.5 on 2026-05-22 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0028_alter_projectredcapmapping_redcap_project_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectredcapmapping',
            name='redcap_project_info',
        ),
    ]
