# Generated by Django 6.0.5 on 2026-05-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0029_remove_projectredcapmapping_redcap_project_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectredcapmapping',
            name='redcap_project_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
