# Generated by Django 6.0.5 on 2026-05-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0030_projectredcapmapping_redcap_project_info'),
        ('promapp', '0028_aiapiconfiguration_utility_function_path_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='redcapformtoquestionnairemapping',
            name='patientapp_redcapformtoquestionnairemapping_date_mapping_required_for_events',
        ),
        migrations.AlterField(
            model_name='redcapformtoquestionnairemapping',
            name='redcap_date_mapping_field',
            field=models.CharField(blank=True, help_text='As the quality of life data will be imported into REDCap, the system will not know which dates should be matched with which event if the form is repeating form or a part of a event or both. In such a situation, we allow the use of a secondary field whose data is already present in the REDCap database to automatically map the questionnaire submission date. For example, if the patient has an event with two forms - one for quality of life and one for a general visit, and the date of the visit is recorded while the quality of life data is to be imported from this application, then assigning this date field in the visit form will allow the system to automatically suggest which submission will map to a specific event. Note that this field is optional and has been provided to reduce the manual data matching required. This is the field in the REDCap form that will be used to map the date to the questionnaire. Note that this field may exist in another form where the visit date is recorded.', max_length=1024, null=True),
        ),
        migrations.AddConstraint(
            model_name='redcapformtoquestionnairemapping',
            constraint=models.CheckConstraint(condition=models.Q(('redcap_date_mapping_field__isnull', True), ('redcap_date_mapping_field', ''), ('redcap_form_is_in_event', True), ('redcap_form_is_repeating', True), ('redcap_event_is_repeating', True), _connector='OR'), name='patientapp_redcapformtoquestionnairemapping_date_mapping_only_for_repeating_or_event', violation_error_message='A date mapping field can only be set when the form is part of an event, is a repeating form, or the event is repeating.'),
        ),
    ]
