# Generated by Django 6.0.5 on 2026-05-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0031_remove_redcapformtoquestionnairemapping_patientapp_redcapformtoquestionnairemapping_date_mapping_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='redcapfieldtoitemmapping',
            name='response_transform',
            field=models.CharField(choices=[('none', 'No transform (use as-is)'), ('to_int', 'Integer (e.g. 1.00 → 1)'), ('to_float', 'Float / decimal (e.g. 1 → 1.0)'), ('to_float_2', 'Float 2 dp (e.g. 1 → 1.00)'), ('round_int', 'Round to nearest integer (e.g. 1.6 → 2)'), ('strip_zeros', 'Strip trailing zeros (e.g. 1.00 → 1, 1.50 → 1.5)')], default='none', help_text="How to coerce the stored response_value string before writing to REDCap. Use 'Integer' when REDCap expects a whole number (radio/dropdown codes, integer fields). Use 'Strip trailing zeros' to remove unnecessary decimal places (e.g. 1.00 → 1).", max_length=20),
        ),
    ]
